# Generated by Django 4.0.3 on 2022-04-04 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clothes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35)),
                ('category', models.CharField(choices=[('SH', 'Shirt'), ('PT', 'Pants'), ('JK', 'Jacket')], default='Shirt', max_length=2)),
                ('size', models.CharField(max_length=16)),
                ('price', models.DecimalField(decimal_places=2, max_digits=20000)),
            ],
        ),
    ]
