# Generated by Django 4.0.3 on 2022-04-04 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothes',
            name='clothing_img',
            field=models.ImageField(default='no_image.png', upload_to=''),
        ),
    ]
