# Generated by Django 4.0.3 on 2022-04-04 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothing', '0002_clothes_clothing_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clothing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35)),
                ('brand', models.CharField(max_length=20)),
                ('category', models.CharField(choices=[('SH', 'Shirt'), ('PT', 'Pants'), ('JK', 'Jacket')], default='Shirt', max_length=2)),
                ('size', models.CharField(max_length=16)),
                ('price', models.DecimalField(decimal_places=2, max_digits=20000)),
                ('clothing_img', models.ImageField(default='no_image.png', upload_to='')),
            ],
        ),
        migrations.DeleteModel(
            name='Clothes',
        ),
    ]
