# Generated by Django 4.0.3 on 2022-04-12 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothing', '0003_clothing_delete_clothes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('CL', 'Clothing'), ('SH', 'Shoes'), ('AC', 'Accessories')], default='Clothing', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35)),
                ('brand', models.CharField(max_length=20)),
                ('category', models.CharField(choices=[('SH', 'Shirt'), ('PT', 'Pants'), ('JK', 'Jacket'), ('NN', 'None')], default='Shirt', max_length=2)),
                ('letter_size', models.CharField(blank=True, max_length=16)),
                ('number_size', models.DecimalField(decimal_places=1, max_digits=4)),
                ('price', models.DecimalField(decimal_places=2, max_digits=20000)),
                ('item_img', models.ImageField(default='no_image.png', upload_to='')),
            ],
        ),
        migrations.DeleteModel(
            name='Clothing',
        ),
    ]
