# Generated by Django 4.0.3 on 2022-04-12 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothing', '0005_alter_items_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.CharField(default='Clothing', max_length=20),
        ),
    ]
