# Generated by Django 4.0.3 on 2022-04-12 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothing', '0007_alter_category_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='number_size',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4),
        ),
    ]
